### ISSUE TITLE
bigger button

### ISSUE THREAD

**Issue by thsrp-bob-roger** [Sebclem/OctoPrint-SimpleEmergencyStop#11]
Is it possible to have a bigger button in the Nav Bar  . Thanks...

**Comment by Andy-ABTec** [comment]
I would support this as well +1 👍

**Comment by Ralnarene** [comment]
Heh, this was pretty much what I was coming here to say.  Can we get a nice big red button?

**Comment by Sebclem** [comment]
Hi!
Sorry for late reply but i'm back for taking care of my plugin !
I'm on it :+1:

**Comment by Sebclem** [comment]
Done ! If you have any sugestion for a better design, just let me know :smile:
