### ISSUE TITLE
breaks the octoprint UI

### ISSUE THREAD

**Issue by adcurtin** [Sebclem/OctoPrint-SimpleEmergencyStop#13]
OctoPrint 1.4.0 running on OctoPi 0.17.0

when I updated this plugin, it broke a ton of the icons in the UI of octoprint. 

home screen - the offset edit pencil is gone

settings - printer profiles - the edit pencil and trashcan are gone

tons of other icons everywhere are busted by this. disabling the plugin has restored my icons.

**Comment by Sebclem** [comment]
Hi,

Can I have a screenshot please?
Which browser are you using?
And the list of other plugin you have installed, it's maybe a conflict with another one.

**Comment by lbussy** [comment]
Confirmed.  Running current Firefox on Windows 10.

![error](https://www.brewbubbles.com/wp-content/uploads/2020/03/PrinterProfile.png)

It also kills a few buttons in Access Control:

![error](https://www.brewbubbles.com/wp-content/uploads/2020/03/AccessControl.png)

I've tried it in a Private Window so all plugins are disabled, it happens there too.

It's worse in IE.  It shows both buttons (large button not enabled) and messes up the top banner:

![error](https://www.brewbubbles.com/wp-content/uploads/2020/03/Banner.png)

I also disabled all of my Octoprint plugins and that had no effect.

**Comment by Sebclem** [comment]
Ok it's normally fixed, just let me know if it's ok for you.

> It's worse in IE. It shows both buttons (large button not enabled) and messes up the top banner:

@lbussy Sorry but it's a true nigthmare to make this plugin compatible with IE, I have gave up :laughing:

**Comment by lbussy** [comment]
[Edited] Updated, seems to work now.  Will continue to poke around.

**Comment by Sebclem** [comment]
You can force check for update with:
- Settings
- Software Update
- Advanced options
- Force check for update

**Comment by adcurtin** [comment]
just updated, all fixed! Thanks for the super quick fix!
