### ISSUE TITLE
Access control; prevent read-only users from firing event

### ISSUE THREAD

**Issue by STaveras** [Sebclem/OctoPrint-SimpleEmergencyStop#15]
I had an issue where a read-only user accidentally hit the Emergency Stop button; I don't think they should be able to do this. Please use octoprint.access.permissions to prevent readonly or guest users from using this button. Thanks!

**Comment by Sebclem** [comment]
Fixed, i'm using the "Control" permission. If you don't have this permission, the button will not show up.

**Comment by STaveras** [comment]
Thanks
