### ISSUE TITLE
Latest update broke my UI

### ISSUE THREAD

**Issue by SleepyBlueCat** [Sebclem/OctoPrint-SimpleEmergencyStop#16]
Hey latest update broke my UI. Some buttons were suddenly missing, it showed the disconnect button but my printer wasn't connected. ![see picture](https://cdn.discordapp.com/attachments/661327037360898063/747035750746554378/unknown.png)

Restarting in safe mode and opening the octoprint log showed me that this plugin was the last one i've updated so i deleted the plugin and now everything is okay again.
![see second image](https://user-images.githubusercontent.com/59633323/90976468-a1e31100-e53d-11ea-9d4b-a1f25186009f.png)

I'd be happy to work on this if you want to test more.
Kind regards

**Comment by Sebclem** [comment]
Can i have your chrome logs ? (F12)

**Comment by SleepyBlueCat** [comment]
I don't think logging in my chrome is turned on? Where do i find it? I pressed F12 but I don't see any logging.
The same UI thing was on my phone and Firefox (pc) as well.

**Comment by Sebclem** [comment]
Normaly, if you press F12, you have the DevTool that open. Just click on the console tab in DevTool window.
You will normaly have something like this:
![image](https://user-images.githubusercontent.com/23737709/90976896-61859200-e541-11ea-8c0f-0fcf3f52fed8.png)

**Comment by SleepyBlueCat** [comment]
there you go. Note that I said that I did delete the plugin. Do you want me to install the latest version again?
![image](https://user-images.githubusercontent.com/59633323/90976928-b1645900-e541-11ea-8f98-cc385681ba49.png)

**Comment by Sebclem** [comment]
Yes please

**Comment by SleepyBlueCat** [comment]
Hmmm i have another issue now... Do you think it would be related?
![image](https://user-images.githubusercontent.com/59633323/90977051-b83f9b80-e542-11ea-912c-60f4c7245cb5.png)

**Comment by SleepyBlueCat** [comment]
i'm gonna restart my router

**Comment by Sebclem** [comment]
Hum very strange, maybe try to reboot the octoprint.
I don't think this 2 bugs are related.

**Comment by SleepyBlueCat** [comment]
I did, even rebooted the pi itself. Gotta figure this out and come back to you.

**Comment by SleepyBlueCat** [comment]
okay, router reboot did it. Installed the plugin again but same thing. Here's the log
![image](https://user-images.githubusercontent.com/59633323/90977296-9ba46300-e544-11ea-8642-4161f52c31a5.png)

**Comment by SleepyBlueCat** [comment]
i can also chat on discord and such if you'd like

**Comment by Sebclem** [comment]
Can i have your octoprint version ?

**Comment by SleepyBlueCat** [comment]
OctoPrint 1.3.12 running on OctoPi 0.17.0

**Comment by Sebclem** [comment]
Ok i think i figured out.
I think something as ben change for user permission between Octoprint 1.3.12 and the last version.
@foosel can you confirm this ?

**Comment by heylael** [comment]
I'm seeing this issue as well - same install from Octopi and then installed the plugin using a zip file. Installed Dashboard plugin, Display Layer Progress, and then Simple Emergency stop, and most of the navbar vanishes. All I have is the Admin menu.

**Comment by SleepyBlueCat** [comment]
I have all the same plugins installed and more.

**Comment by foosel** [comment]
> I think something as ben change for user permission between Octoprint 1.3.12 and the last version.
> @foosel can you confirm this ?

The permission system was literally rewritten in 1.4.0, see also the release notes ;) https://github.com/OctoPrint/OctoPrint/releases/tag/1.4.0

Your plugin as is seems to not be compatible to 1.3.x and needs at least 1.4.0.

**Comment by SleepyBlueCat** [comment]
@Sebclem Is there a sollution?

**Comment by Sebclem** [comment]
Easy and fast fix: Upgrade your octoprint to 1.4.0+

For older version, I will take a look.

**Comment by Sebclem** [comment]
I have made a new release that will normally prevent this issue, please confirm me that, but like i say in the readme [here](https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop#permission):

> ### __Octoprint < 1.4.0:__
>
> If you are running __Octoprint < 1.4.0__, there is no permission check, every user can access to the emergency stop button (as soon as they are logged in).
>
> __This is why I highly recommend to upgrade your octoprint to > 1.4.0__
