### ISSUE TITLE
Command line install failed

### ISSUE THREAD

**Issue by frankvdh** [Sebclem/OctoPrint-SimpleEmergencyStop#2]
I don't know what this means. Installing via the plugin manager worked just fine.

pi@pi3:~ $ pip install "https://github.com/BrokenFire/OctoPrint-SimpleEmergencyStop/archive/master.zip"
Collecting https://github.com/BrokenFire/OctoPrint-SimpleEmergencyStop/archive/master.zip
  Downloading https://github.com/BrokenFire/OctoPrint-SimpleEmergencyStop/archive/master.zip
     - 10kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-AZiJ2y-build/
pi@pi3:~ $

**Comment by Sebclem** [comment]
Hum, very strange...
May be somme dependencies, the most strange is install work whit plugin manager....

**Comment by BrokenFire** [comment]
Are you sure you are under the venv?

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sebclem** [comment]
Are you sure you are under the venv?

**Comment by frankvdh** [comment]
Hi,

Sorry, I have no idea. What's a venv? How can I tell if I'm under it?

I logged into my Pi via ssh as 'pi', then pasted the command.

Does it matter what directory you're in when you run the command? Do you
maybe have to be in superuser mode?

Frank

**Comment by Sebclem** [comment]
Ah ok, 
Well a venv (virtual environment) is an environment where all dependences of octoprint is installed, to activate it, when you're on pi home :
`source Octoprint/venv/bin/activate`
And now you can normally see `(venv)` before you're user name.

You don't need to run it as SU, and normally the folder doesn't matter but you need to activate the venv for all octoprint command.

**Comment by frankvdh** [comment]
Ah OK. :)

Not sure why I'd want a venv. Seems to me that another layer of abstraction
is going to cost something for no benefit (except for command-line
installation of plugins :) )

Happy to leave it at this; really just wanted to document something that
didn't work in case someone else encountered it.

Thanks for your work on this plugin.

Frank

**Comment by Sebclem** [comment]
Ah ok, thank for reporting 😉
