### ISSUE TITLE
Plugin sends emergency stop when reloading the OctoPrint UI.

### ISSUE THREAD

**Issue by cshunsinger** [Sebclem/OctoPrint-SimpleEmergencyStop#3]
After the thing was printing for 3 hours, I reloaded the OctoPrint ui. It took about a minute for the UI to display the printer status. Except instead of displaying the printer status, your plugin sent an emergency stop to the printer.

I did not click anything to trigger an emergency stop. In the settings your plugin is set to give me a warning prompt. I did not even receive a warning prompt.

I would advise against installing this plugin.

**Comment by Sebclem** [comment]
Oh sorry for ruining your printing :/ 

I check this bug after work (French hour)

Thanks for reporting bug and sorry again :/

**Comment by copystring** [comment]
Same here and the button is also gone...

**Comment by Sebclem** [comment]
The button is only visible when you are logged in and printer connected, i will try to correct the bug of auto send tonight

**Comment by copystring** [comment]
Oh yes. For some reason I got logged out just after updating the plugin.

**Comment by Sebclem** [comment]
Done! Thx for reporting 👍
