### ISSUE TITLE
Icon not displayed in the top menu

### ISSUE THREAD

**Issue by ZeroScars** [Sebclem/OctoPrint-SimpleEmergencyStop#4]
After re-install of OctoPrint on a RPi and adding all plugins again, the icon of this plugin is not displayed in the top menu bar.

**Comment by BrokenFire** [comment]
Hi,
Sorry for late reply!
Are you login in and your printer is connected? The icon is visible only on this 2 conditions 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sebclem** [comment]
Hi,
Sorry for late reply!
Are you logged in and your printer is connected? The icon is visible only on this 2 conditions.

**Comment by ZeroScars** [comment]
Yes, but it still does not display

**Comment by Sebclem** [comment]
Whitch version of octoprint ?

**Comment by ZeroScars** [comment]
I'll check in a few days, I'm on holiday,
Thanks!

Op 29 aug. 2017 12:40 a.m. schreef "BrokenFire" <notifications@github.com>:

**Comment by ZeroScars** [comment]
I'm on the latest official release, no beta or release candidate.

Still no luck in deinstall/install.

Oscar

Op 29 aug. 2017 1:05 a.m. schreef "Zero Scars" <zeroscars@gmail.com>:

**Comment by Sebclem** [comment]
topical response but have you tried to re-install it ? if yes, have you errors on Octoprint logs ?

**Comment by ZeroScars** [comment]
I will reinstall it again and see if there are error messages. Can't
remember from last installment.

Oscar

Op 17 sep. 2017 12:09 p.m. schreef "Sébastien Clément" <
notifications@github.com>:

**Comment by Sebclem** [comment]
You can also restart your pi and look a the logs on ~/. ocotoprint/logs if you have errors on startup

**Comment by ZeroScars** [comment]
After a de-installation and installation it not appears (not showing the icon) again. Also restarted the PI. Thanks. Glad it works again.
