### ISSUE TITLE
Icon Appears While Not Logged In

### ISSUE THREAD

**Issue by Sunoo** [Sebclem/OctoPrint-SimpleEmergencyStop#5]
The icon appears and seems to work fine when logged in, however, it is also appearing while not logged in (I didn't try to see if it actually worked then, but I did bring up the warning dialog). I'm not sure if that is what is expected from your plugin, but it feels like either a bad idea or a bug.

**Comment by Sebclem** [comment]
Hi, i will take a look to this, I have don't seen this bug on my ocotoprint because I'm auto loged on.
I correct this bug as soon as possible

**Comment by Sunoo** [comment]
If it makes a difference, I'm running 1.3.5rc2. I hadn't tried this plugin before this version, so I don't know if something broke or not.

**Comment by franzbischoff** [comment]
here it appears when not logged in too... I haven't tried to press it yet beause I'm in the middle of a print :-)

I'll try later to see if it really stops even when logged off.

**Comment by franzbischoff** [comment]
Tested. It shows the confirmation dialog, but even after confirming, the printer is not "killed" when not logged in

**Comment by Sebclem** [comment]
Ok thanks for testing, anyway I will try to fix the icon when I have time.

Thanks you guys! ;)

**Comment by Sebclem** [comment]
Bug Fixed ! Thanks for reporting ;)
